# Generated by Django 5.0.2 on 2024-11-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Руководитель'), ('EMPLOYEE', 'Сотрудник'), ('OBSERVER', 'Наблюдатель'), ('MAIN_EMPLOYEE', 'Главный сотрудник')], default='EMPLOYEE', max_length=50, verbose_name='Рол'),
        ),
    ]
