# Generated by Django 5.0.2 on 2024-11-04 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('importance', models.CharField(choices=[('low', 'низкий'), ('medium', 'средний'), ('high', 'высокий')], default='low', max_length=255, verbose_name='Важность заявки')),
                ('status', models.CharField(choices=[('primary', 'первичная'), ('corrected', 'исправленное')], default='primary', max_length=255, verbose_name='Статус заявки')),
                ('created_date', models.DateTimeField(verbose_name='Дата создания заявки')),
                ('supplier', models.CharField(max_length=300, verbose_name='Поставщик')),
                ('initiator', models.CharField(max_length=255, verbose_name='Инициатор заявки')),
                ('contract_number', models.CharField(max_length=255, unique=True, verbose_name='Номер договора')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('payment_percentage_amount', models.FloatField(default=0, verbose_name='Процент от Сумма оплаты')),
                ('payment_method', models.CharField(blank=True, default='Безналичный расчет', max_length=255, null=True, verbose_name='Метод оплаты')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='application.application')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationReconciliators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('role', models.CharField(choices=[('ADMIN', 'Руководитель'), ('EMPLOYEE', 'Сотрудник'), ('OBSERVER', 'Наблюдатель')], default='EMPLOYEE', max_length=255, verbose_name='Роль')),
                ('sequence_hierarchy', models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер в иерархии')),
                ('status', models.CharField(choices=[('СONFIRMED', 'Подтвержден'), ('NOT_CONFIRMED', 'Не подтвержден'), ('CANCELED', 'Отменен')], default='NOT_CONFIRMED', max_length=255, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliators', to='application.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Согласователь',
                'verbose_name_plural': 'Согласователи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTotalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('budget_code', models.CharField(max_length=255, unique=True, verbose_name='Код бюджета')),
                ('direction', models.CharField(max_length=255, verbose_name='Направление')),
                ('object', models.CharField(max_length=255, verbose_name='Объект')),
                ('nomenclature', models.CharField(max_length=500, verbose_name='Номенклатура')),
                ('unit_of_measurement', models.CharField(max_length=255, verbose_name='Единица измерения')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
                ('VAT_rate', models.FloatField(default=0, verbose_name='Ставка НДС')),
                ('VAT_amount', models.FloatField(default=0, verbose_name='Сумма НДС')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_amounts', to='application.application')),
            ],
            options={
                'verbose_name': 'Сумма ИТОГО',
                'verbose_name_plural': 'Суммы ИТОГИ',
                'ordering': ['-id'],
            },
        ),
    ]
