# Generated by Django 5.0.2 on 2024-11-05 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationreconciliators',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Текущий согласователь'),
        ),
        migrations.AlterField(
            model_name='applicationpayment',
            name='payment_percentage_amount',
            field=models.FloatField(default=0, verbose_name='Процент от Сумма оплаты (в процентах %)'),
        ),
        migrations.AlterField(
            model_name='applicationreconciliators',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliators', to='application.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='applicationreconciliators',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='Согласователь'),
        ),
        migrations.AlterField(
            model_name='applicationtotalamount',
            name='VAT_rate',
            field=models.FloatField(default=0, verbose_name='Ставка НДС (в процентах %)'),
        ),
    ]
