# Generated by Django 5.0.2 on 2024-11-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_applicationreconciliators_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationreconciliators',
            name='current_status',
        ),
        migrations.AddField(
            model_name='application',
            name='current_status',
            field=models.CharField(choices=[('СONFIRMED', 'Подтвержден'), ('NOT_CONFIRMED', 'Не подтвержден'), ('CANCELED', 'Отменен')], default='NOT_CONFIRMED', max_length=255, verbose_name='Текущий статус'),
        ),
    ]
