# Generated by Django 5.0.2 on 2024-11-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_applicationreconciliators_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='тип заявки'),
        ),
        migrations.AlterField(
            model_name='applicationreconciliators',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Руководитель'), ('EMPLOYEE', 'Сотрудник'), ('OBSERVER', 'Наблюдатель'), ('MAIN_EMPLOYEE', 'Главный сотрудник')], default='EMPLOYEE', max_length=255, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('document_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название файла')),
                ('document', models.FileField(upload_to='application/documents/', verbose_name='Документ (файл)')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='application.application', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'Документ заявок',
                'verbose_name_plural': 'Документы заявок',
                'ordering': ['-id'],
            },
        ),
    ]
