# Generated by Django 5.0.2 on 2025-05-06 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_application_application_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='purchase_reconciliations_status',
            field=models.CharField(choices=[('СONFIRMED', 'Подтвержден'), ('NOT_CONFIRMED', 'Не подтвержден'), ('CANCELED', 'Отменен')], default='NOT_CONFIRMED', max_length=255, verbose_name='Текущий статус от закупа'),
        ),
        migrations.CreateModel(
            name='ApplicactionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('number', models.CharField(max_length=500, verbose_name='Номер (Материала||Услуг)')),
                ('type', models.CharField(choices=[('SERVICE', 'Услуга'), ('MATERIAL', 'Материал')], default='MATERIAL', max_length=15, verbose_name='Тип')),
                ('unit_of_measurement', models.CharField(max_length=200, verbose_name='Единица Измерения')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
                ('brand', models.CharField(max_length=250, verbose_name='Марка')),
                ('budget_code', models.CharField(max_length=250, verbose_name='Бюджетный код')),
                ('status', models.CharField(choices=[('СONFIRMED', 'Подтвержден'), ('NOT_CONFIRMED', 'Не подтвержден'), ('CANCELED', 'Отменен')], default='NOT_CONFIRMED', max_length=100, verbose_name='Статус')),
                ('quantity_agreed', models.FloatField(blank=True, default=0, null=True, verbose_name='Согласованное количество')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='application.application', verbose_name='Заявка')),
                ('canceled_from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_materials', to=settings.AUTH_USER_MODEL, verbose_name='Отменено от пользователя')),
            ],
            options={
                'verbose_name': 'Материал Заявки',
                'verbose_name_plural': 'Материалы Заявки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPurchaseReconciliators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('role', models.CharField(choices=[('ADMIN', 'Руководитель'), ('EMPLOYEE', 'Сотрудник'), ('OBSERVER', 'Наблюдатель'), ('MAIN_EMPLOYEE', 'Главный сотрудник')], default='EMPLOYEE', max_length=255, verbose_name='Роль')),
                ('sequence_hierarchy', models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер в иерархии')),
                ('status', models.CharField(choices=[('СONFIRMED', 'Подтвержден'), ('NOT_CONFIRMED', 'Не подтвержден'), ('CANCELED', 'Отменен')], default='NOT_CONFIRMED', max_length=255, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий согласователь')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_reconciliations', to='application.application', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='Согласователь')),
            ],
            options={
                'verbose_name': 'Согласователь Закупа',
                'verbose_name_plural': 'Согласователи Закупа',
                'ordering': ['-id'],
            },
        ),
    ]
